theme: jekyll-theme-leap-day
title: VMware Events Broker Appliance
description: The vCenter Event Broker Appliance enables customers to easily create event-driven automation based on vCenter Server Events
show_downloads: false
github:
  zip_url: https://github.com/parth33bank/vcenter-event-broker-appliance/archive/master.zip
  fling_url: https://flings.vmware.com/vcenter-event-broker-appliance
