toc:
  - title: Introduction
    subfolderitems:
      - page: About
        id: intro-about
        url: /kb 
      - page: Architecture
        id: intro-architecture
        url: /kb/architecture
      - page: VMware Event Router
        id: intro-event-router
        url: /kb/event-router
      - page: Functions
        id: intro-functions
        url: /kb/functions

  - title: Install
    subfolderitems:
      - page: Event Processor - OpenFaaS
        id: install-openfaas
        url: /kb/install-openfaas
      - page: Event Processor - AWS EventBridge
        id: install-eventbridge
        url: /kb/install-eventbridge

  - title: Use
    subfolderitems:
      - page: Event Provider - vCenter
        id: use-vcenter-events
        url: /kb/vcenter-events
      - page: Deploy Functions
        id: use-functions
        url: /kb/use-functions

  - title: Contribute
    subfolderitems:
      - page: Getting Started
        id: contribute-start
        url: /kb/contribute-start
      - page: Build Functions
        id: contribute-functions
        url: /kb/contribute-functions
      - page: Build Event Router
        id: contribute-eventrouter
        url: /kb/contribute-eventrouter
      - page: Build Appliance
        id: contribute-appliance
        url: /kb/contribute-appliance
      - page: Build Website
        id: contribute-site
        url: /kb/contribute-site

  - title: Advanced
    subfolderitems:
      - page: Deploy as Kubernetes App
        id: advanced-deploy-k8s
        url: /kb/advanced-deploy-k8s
      - page: Update TLS Certificates
        id: advanced-certificates
        url: /kb/advanced-certificates
  
  - title: Troubleshoot
    subfolderitems:
      - page: Troubleshooting Appliance
        id: troubleshoot-appliance
        url: /kb/troubleshoot-appliance
      - page: Troubleshooting Functions
        id: troubleshoot-functions
        url: /kb/troubleshoot-functions

  - title: More..
    subfolderitems:
      - page: FAQ
        id: site-faq
        url: /faq
      - page: Resources
        id: site-resources
        url: /resources